version: "3.8"
services:
  django:
    build:
      context: ../
      dockerfile: docker/Dockerfile-django
    command: bash -c "cd code/src &&
                      python manage.py makemigrations main &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ..:/code
    ports:
      - ${DJANGO_PORT}:8000
    env_file:
        - ./.env
    restart: always
