FROM python:3
ENV PYTHONUNBUFFERED 1


# Create code source code folder
RUN mkdir /code


# Upgrade pip
RUN pip3 install --no-cache-dir --upgrade pip


# Install python packet
COPY docker/requirements.txt /
RUN pip install -r requirements.txt


# Copy source code to docker
ADD . /code
